// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: internal.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalRoutesClient is the client API for InternalRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalRoutesClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type internalRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalRoutesClient(cc grpc.ClientConnInterface) InternalRoutesClient {
	return &internalRoutesClient{cc}
}

func (c *internalRoutesClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/InternalRoutes/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalRoutesClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/InternalRoutes/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalRoutesServer is the server API for InternalRoutes service.
// All implementations must embed UnimplementedInternalRoutesServer
// for forward compatibility
type InternalRoutesServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedInternalRoutesServer()
}

// UnimplementedInternalRoutesServer must be embedded to have forward compatible implementations.
type UnimplementedInternalRoutesServer struct {
}

func (UnimplementedInternalRoutesServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedInternalRoutesServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedInternalRoutesServer) mustEmbedUnimplementedInternalRoutesServer() {}

// UnsafeInternalRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalRoutesServer will
// result in compilation errors.
type UnsafeInternalRoutesServer interface {
	mustEmbedUnimplementedInternalRoutesServer()
}

func RegisterInternalRoutesServer(s grpc.ServiceRegistrar, srv InternalRoutesServer) {
	s.RegisterService(&InternalRoutes_ServiceDesc, srv)
}

func _InternalRoutes_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalRoutesServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InternalRoutes/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalRoutesServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalRoutes_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalRoutesServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InternalRoutes/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalRoutesServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalRoutes_ServiceDesc is the grpc.ServiceDesc for InternalRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InternalRoutes",
	HandlerType: (*InternalRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _InternalRoutes_Health_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _InternalRoutes_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
